version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: auctions_db
      POSTGRES_USER: auctions_user
      POSTGRES_PASSWORD: pAI5ku5V.&22,X[
    ports:
      - "5432:5432"
      
  web:
    build: .
    command: >
      sh -c "watchmedo auto-restart --pattern=*.py --recursive -- python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "3000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: auctions_app.settings
      DEBUG: '1'
      DJANGO_ALLOWED_HOSTS: localhost
      POSTGRES_DB: auctions_db
      POSTGRES_USER: auctions_user
      POSTGRES_PASSWORD: pAI5ku5V.&22,X[
      POSTGRES_HOST: db
    depends_on:
      - db

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"  # Expose Redis on the default port

volumes:
  postgres_data:
